### PR TITLE
Module Backbone Tutorial: Mining Github for Contributor Gold

### PR DESCRIPTION
**Pull request by headwinds**
I've made a contribution to the modular backbone tutorial. I thought I'd flesh out the pages a bit more with some sample data pulled directly from Github about this project and all the awesome contributors.  

Everything works fine locally however when I host the example I run into CORS issues which I hope you can then help me resolve. 

http://backbonetutorials.com/cross-domain-sessions/ <-- I'm sure the answer is in here ;-D

### CODE REVIEW

**Comment by thomasdavis** [comment]
http://weknowmemes.com/wp-content/uploads/2011/12/mother-of-god-meme.jpg

**Comment by thomasdavis** [comment]
Hey Brandon, great work so far.  I updated it to include boot strap to try get it looking nicer and I fixed up the cross domain errors by making it jsonp and returning the correct data in the parse methods of the models.

I ran out of API calls to github for today so can't test anything more but will be adding more additions. 

Will also add a notice on the example of your help with it.

**Comment by headwinds** [comment]
brilliant! I ran out of steam yesterday when I finished my view experiments
and went to try them online to suddenly discovered those CORS issues - I
threw in the towel at that point and thought it time to let you in on what
I was up to…

I'm super happy you like the addition. I didn't want to go to far and
dilute the goal of the example to learn how backbone and require.js work
together.

I thought I do something simple on the home view, and then increase the
complexity from the Projects to Contributors views; make it look more like
a website with both text and images. I also found myself referring to your
other tutorials while developing.
I'll check out your updates! I also let you know that this tutorial has
been a major selling point at our office in Toronto - I'm a senior
interface developer at Blast Radius (www.blastradius.com) - I shared the
tutorial with other developers and we've adopted this approach on our
client projects -- we're all are really stoked about requirejs now.

**Comment by thomasdavis** [comment]
Great to hear! should have a quick look at AMD(https://github.com/amdjs/amdjs-api/wiki/AMD) which is the spec implemented by require.js.

building AMD projects makes script concatenation look like a stone age tool.

backbone can be used in many ways and I hope you guys have as much success with it as I have.

**Comment by thomasdavis** [comment]
I will be doing more updates(including a more prominent link to your contribution) on top of what you have contributed over the week. Thanks again!

**Pull request merged**
