### PR TITLE
Fixed a typo where "exist" should be "exists"

### PR DESCRIPTION
**Pull request by ClimbsRocks**
Exists in lines 222 and 248 matches the singular nouns it is being used with. "Exist" had a mismatch where it expected plural nouns.

image

### CODE REVIEW

**Comment by thomasdavis** [comment]
Thanks Preston, excellent moustache!

**Comment by ClimbsRocks** [comment]
Thanks Thomas! I was horrifically lost on Backbone until I found your site. It's easily the best learning resource I've found for it yet. 

The "mo" was from a trip to New Zealand where I felt obliged to boost my manliness to keep up with the local Kiwis : )

**Comment by thomasdavis** [comment]
aha my ex girlfriend use to make me feel insecure by calling them "genetically blessed"

**Comment by ClimbsRocks** [comment]
My Kiwi friends will love to hear that comment! This one just made my night.

**Pull request merged**
