### PR TITLE
Phpversion for the Backbone.js Beginner Video Tutorial

### PR DESCRIPTION
**Pull request by raphaelbaer**
Hello,

Thanks for the tutorial about BlackBone. It is great to understand how it works.

After tested it with your Heroku server, I wanted to try with my own php server.
Then I wrote a minimal php script.
It may interest others.
I put everything in phpversion folder.

best
Raphael

### CODE REVIEW

**Comment by headwinds** [comment]
is this a new tutorial? or did you take one of the existing tutorials and add your PHP server option? It sounds like you used an existing backbone tutorial - which one? 

I think we can probably find a way to work in your update... just need to know where it best fits. Do you happen to have a working demo so we can see it in action? If so, please post the url to the demo.

Are you also storing any data in MySQL?

**Comment by raphaelbaer** [comment]
This is the Backbone tutorial from Thomas Davis. I added a php server option.
Here is the link : https://github.com/thomasdavis/backbonetutorials/tree/gh-pages/videos/beginner

Inside this folder, I added a new folder "phpversion" with the php server side (Thomas made a node.js server).
I put the client again with the new link to the php server.

There is no MySQL database, data are stored in a file, then, it can work easily (the tutorial is about the backbone part and not the server part).

So far, there is no working demo.

**Comment by headwinds** [comment]
Ok it appears the original also doesn't have a working demo which I'd think isn't that great since its aimed a beginner, and most beginners like to see things in actions. Actually doesn't everyone?!

Could you possibly a host a version of your demo? 

I think one of Thomas' goals for this github repo was to work with primarily Javascript related technologies ( node, mongoDB). If we accept a PHP version, we might be opening the door for more non javascript servers (java, python, etc). But I think we should make an exception in this case and then add a bit more guidelines around what we want from contributors or else they're just shooting in the dark. 

I think this might be a good example for developers to compare PHP vs Node. 

So Thomas, should we merge this? No harm eh?!

**Comment by raphaelbaer** [comment]
Great, I hope it will help !!

**Pull request merged**
